services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .api.env  # Arquivo de variáveis da API
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15
    env_file:
      - .db.env  # Arquivo de variáveis do banco de dados
    ports:
      - "5434:5432"
